### ISSUE TITLE
Key error at line 135

### ISSUE THREAD

**Issue by joxerx** [bibajz/bitcoin-python-async-rpc#21]
Probably found a bug [here](https://github.com/bibajz/bitcoin-python-async-rpc/blob/master/src/bitcoinrpc/bitcoin_rpc.py#L135) 
Try to change line to:
```
if content.get("error") is not None:
    raise RPCError(content["error"]["code"], content["error"]["message"])
```

**Comment by bibajz** [comment]
Closed via #22
